### PR TITLE
Add quantized CTranslate2 exporters

### PR DESCRIPTION
**Pull request by guillaumekln**

### CODE REVIEW

**Comment by panosk** [comment]
Great addition! I'd like to ask though, do quantized models work on non-Intel CPUs?

**Comment by guillaumekln** [comment]
Yes, see the table here: https://github.com/OpenNMT/CTranslate2#quantization-and-reduced-precision

**Comment by panosk** [comment]
Nice! IIRC, long ago it was not possible, so I was using `int8` at runtime to be sure quantization would happen only on Intel.

**Comment by guillaumekln** [comment]
Yes, that's possible. Now there is a runtime check to determine the CPU and select a backend accordingly. If the selected backend does not support a quantized type (e.g. int16 on AMD) we automatically fallback to another type according to the table.

**Comment by panosk** [comment]
OK, just to make it clear: that was my thought before and that's why I was not exporting quantized models and I was using quantization only on runtime. This implied that the model was not already quantized to a type that couldn't be converted in runtime --that is, an exported INT8 model couldn't be converted to INT16 or float. Now my understanding is that I can safely export a model to INT8 and be sure that it will run at least in Intel and AMD.

Do I get it right?

**Comment by guillaumekln** [comment]
> Now my understanding is that I can safely export a model to INT8 and be sure that it will run at least in Intel and AMD.

Yes. You can choose any quantization type for export and we ensure the model can be loaded and executed on any hardware. As mentioned, it possibly means converting to another quantization type as described in the table linked above.

**Pull request merged**
