### PR TITLE
Updated Tokenizer doc

### PR DESCRIPTION
**Pull request by R1j1t**
I have made small updates to the tokenizer doc, please provide your feedback. I will extend this idea of `usage` in other docs if accepted

### CODE REVIEW

**Comment by guillaumekln** [comment]
Thanks for contributing.

I'm not convinced to add this kind of usage sections as they duplicate the `-h` flag of the command line scripts. However, the documentation can invite users to read `-h` for more details (as is done in the main README for example).

**Comment by R1j1t** [comment]
I understand. I thought of it but the idea of adding `usage` came from OpenNMT-py, where [training](http://opennmt.net/OpenNMT-py/options/train.html) and [preprocessing](http://opennmt.net/OpenNMT-py/options/preprocess.html) had separate pages explaining the different parameters to pass. 

@guillaumekln I was thinking from a new users point of view, so a more verbose documentation could be more helpful. If you have any ideas for the documentation I can try on that lines.

**Comment by guillaumekln** [comment]
> I understand. I thought of it but the idea of adding usage came from OpenNMT-py, where training and preprocessing had separate pages explaining the different parameters to pass.

The key difference is that this part of the OpenNMT-py documentation is generated from the code. Otherwise it's too much work to keep implementation and documentation in sync.

> @guillaumekln I was thinking from a new users point of view, so a more verbose documentation could be more helpful. If you have any ideas for the documentation I can try on that lines.

For new users, more tutorials/examples might be helpful. Although the quickstart section in the README and the [WMT scripts](https://github.com/OpenNMT/OpenNMT-tf/tree/master/scripts/wmt) already act as a end-to-end examples. Do you think that is not enough to get users started in using the toolkit?

**Comment by R1j1t** [comment]
When I first started using the documentation I had a problem connecting the dots, in the sense that config files were not something I used for modelling. Hence I wanted to make that explicit instead of someone opening config files and trying to understand the use. 

Examples would definitely help, and the current examples help one run the first translation but the next step, moulding to ones use case is something I found difficult.

**Pull request closed without merging**
