### PR TITLE
Support coverage penalty during beam search

### PR DESCRIPTION
**Pull request by guillaumekln**

### CODE REVIEW

**Comment by BigFishMaster** [comment]
Could you tell me how the ```coverage_penalty``` works?
I debug this code and find the shape of ```coverage_penalty``` is ```batch_size*beamIsze``` at the line 218:
https://github.com/OpenNMT/OpenNMT-tf/blob/d34f72246225f30c59a6d3bb499611519f205fa1/opennmt/utils/decoding.py#L218

**Comment by guillaumekln** [comment]
Do you mean the theory behind or how it is implemented? For the theory, it comes from https://arxiv.org/pdf/1609.08144.pdf. For the implementation, it is heavily inspired by https://github.com/tensorflow/tensorflow/commit/f02a2fad042bc401f3d1c89a9fd52e40ca5d1835.

**Comment by BigFishMaster** [comment]
@guillaumekln I read the abstract which has this sentence:
```latex
Our beam search technique employs a length-normalization
procedure and uses a coverage penalty, which encourages generation of an output sentence that is most
likely to cover all the words in the source sentence.
```
Does this mean beam searching results having higher score will have higher coverage ratio? 
I also see the coverage loss from ```https://arxiv.org/pdf/1704.04368.pdf```.  I confuse them..
image

**Comment by guillaumekln** [comment]
It means hypotheses will be penalized if the sum of the attention vectors does not cover well the source sentence. This assumes that attention vectors can be interpreted as soft alignments (which is not true for Transformer models unless trained with guided alignment).

Coverage loss is used for training while coverage penalty is used in beam search.

**Comment by BigFishMaster** [comment]
@guillaumekln do you have any material for guided alignment?

**Comment by guillaumekln** [comment]
See https://arxiv.org/abs/1607.01628

**Comment by BigFishMaster** [comment]
@guillaumekln Thanks

**Pull request merged**
