### PR TITLE
Experimental batch size autotuner

### PR DESCRIPTION
**Pull request by guillaumekln**

### CODE REVIEW

**Comment by vince62s** [comment]
interesting, but would it be more efficient to select also the longest example to be sure of the calculation. Is it working on several gpu (eg different ram size) ?

**Comment by guillaumekln** [comment]
> would it be more efficient to select also the longest example to be sure of the calculation

As it applies to token-based batch only, I assume each batch has an almost constant memory usage. At least during my tests, the automated process correctly found the empirical batch size by only sampling 5 training iterations.

> Is it working on several gpu (eg different ram size) ?

Do you mean several GPUs with different memory? No. This is not even supported currently.

Here it just runs the training in the same condition for a few iterations and check for OOM errors until a "good enough" batch size is found.

**Comment by vince62s** [comment]
well in fact there are still significant variances between batches when average length is very long vs short when you don't trim too much (eg seq_len about 120 or more).
I think fairseq also has a dynamic way of disgarding OOM batches while keeping the training.

**Comment by guillaumekln** [comment]
I'm restricting the available memory to 90% during this auto-selection, hopefully this can absorb the remaining variance. Large scale experiments would be required to confirm the approach, though I don't expect it to be bullet proof.

**Pull request merged**
